# Cloud Run service configuration for AI Legal Companion Frontend
# Static file serving with CDN integration

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-legal-companion-frontend
  namespace: default
  labels:
    app: ai-legal-companion
    component: frontend
    environment: production
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        app: ai-legal-companion
        component: frontend
        version: v1
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "50"
        autoscaling.knative.dev/target: "100"
        
        # Resource allocation (lighter for static serving)
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        
        # Security
        run.googleapis.com/execution-environment: "gen2"
        run.googleapis.com/sandbox: "gvisor"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 60
      serviceAccountName: ai-legal-companion-frontend-sa
      
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/ai-legal-companion-frontend:latest
        
        ports:
        - name: http1
          containerPort: 80
          protocol: TCP
        
        env:
        - name: NODE_ENV
          value: "production"
        - name: BACKEND_URL
          value: "https://api.ai-legal-companion.com"
        
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

  traffic:
  - percent: 100
    latestRevision: true

---
# Service for staging/preview deployments
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-legal-companion-frontend-staging
  namespace: default
  labels:
    app: ai-legal-companion
    component: frontend
    environment: staging
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      labels:
        app: ai-legal-companion
        component: frontend
        version: staging
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/memory: "256Mi"
        run.googleapis.com/cpu: "0.5"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 60
      serviceAccountName: ai-legal-companion-frontend-sa
      
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/ai-legal-companion-frontend:staging
        
        ports:
        - name: http1
          containerPort: 80
          protocol: TCP
        
        env:
        - name: NODE_ENV
          value: "staging"
        - name: BACKEND_URL
          value: "https://api-staging.ai-legal-companion.com"
        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"

  traffic:
  - percent: 100
    latestRevision: true